apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "configName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  DB_USER: "playground"
  DB_DATABASE: "playground"
  JWT_AUDIENCE: {{ .Values.appConfiguration.jwt.audience | quote }}
  JWT_DOMAIN: {{ .Values.appConfiguration.jwt.domain | quote }}
  APP_PORT: {{ .Values.appConfiguration.port | quote }}
