{{- if .Values.ingress.enabled -}}
{{- $fullName := printf "%s-%s" (include "chart.fullname" .) "-ingress" -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - http:
        paths:
          - path: /playground(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "chart.fullname" . }}-service
                port:
                  number: {{ $svcPort }}
{{- end }}
