{{- $secretName := include "secretName" . -}}
{{- $secretObj := lookup "v1" "Secret" .Release.Namespace $secretName | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "retrieveOrComputeSecret" (list $secretData "DB_PASSWORD" .Values.postgres.playground) | indent 2 }}
  INSEE_CONSUMER_KEY: {{ .Values.appConfiguration.insee.consumerKey | b64enc | quote }}
  INSEE_CONSUMER_SECRET: {{ .Values.appConfiguration.insee.consumerSecret| b64enc | quote }}
  MINDEE_API_KEY: {{ .Values.appConfiguration.mindee.apiKey | b64enc | quote }}
