{{- $secretName := include "secretName" . -}}
{{- $secretObj := lookup "v1" "Secret" .Release.Namespace $secretName | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  {{- include "retrieveOrComputeSecret" (list $secretData "DB_PASSWORD" .Values.postgres.playground) | indent 2 }}
  INSEE_BASE64_CONSUMER_KEY_SECRET: {{ .Values.appConfiguration.insee.consumerKeySecretBase64 | quote }}
  MINDEE_API_KEY: {{ .Values.appConfiguration.mindee.apiKey | quote }}