ktor:
  application:
    id: kotlin-playground
  deployment:
    port: 3001
  development: true
jwt:
  domain: $JWT_DOMAIN
  audience: $JWT_AUDIENCE
insee:
  baseApi: "$INSEE_BASE_API:api.insee.fr"
  siretApi: "$INSEE_SIRET_API:entreprises/sirene/V3/siret"
  authenticationApi: "$INSEE_AUTHENTICATION_API:token"
  base64ConsumerKeySecret: $INSEE_BASE64_CONSUMER_KEY_SECRET
  tokenValiditySeconds: 10
mindee:
  apiKey: $MINDEE_API_KEY