ktor:
  application:
    id: kotlin-playground
  deployment:
    port: "$APP_PORT:3001"
  development: true
jwt:
  domain: $JWT_DOMAIN
  audience: $JWT_AUDIENCE
insee:
  baseApi: "$INSEE_BASE_API:api.insee.fr"
  siretApi: "$INSEE_SIRET_API:entreprises/sirene/V3.11/siret"
  authenticationApi: "$INSEE_AUTHENTICATION_API:token"
  consumerKey: $INSEE_CONSUMER_KEY
  consumerSecret: $INSEE_CONSUMER_SECRET
  tokenValiditySeconds: 10
mindee:
  apiKey: $MINDEE_API_KEY
postgres:
  enabled: true
  port: "$DB_PORT:5432"
  host: "$DB_HOSTNAME:localhost"
  database: "$DB_DATABASE:dummy_database"
  user: "$DB_USER:dummy_user"
  password: "$DB_PASSWORD:dummy_password"
