name: CI
on:
  push:
    branches:
      - main
  pull_request:

#  workflow_call:
#    inputs:
#      skip-tests:
#        description: Disable tests execution
#        type: boolean
#        default: false
#        required: false

jobs:
  checks:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '19.0.2'
          distribution: 'zulu'
          architecture: 'x64'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
      - name: Linter check
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          arguments: spotlessCheck
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          arguments: build
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          arguments: test